name: action 
concurrency: 
  group: secret-tv-access
  cancel-in-progress: true
on:
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  action:
    environment:
        name: secret-tv-access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Add PNPM to Path
        run: echo $PNPM_HOME >> $GITHUB_PATH
        env:
          PNPM_HOME: "/home/runner/.local/share/pnpm"
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: |
            - args: [--global, node-gyp]
              cwd: "." 
            - cwd: "." 
        env:
          CXX: gcc
          PNPM_HOME: "/home/runner/.local/share/pnpm"
      - name: Run with pnpm
        run: |
          pnpm action ${{secrets.MY_TOKEN}} ${{secrets.CLIENT_ID}} ${{secrets.MASTER_PASS}}
