name: activation step
permissions:
  contents: read
  deployments: write
on:
  workflow_call:
    inputs:
      client:
        required: true
        type: string
      encrypted:
        required: false
        type: string
    secrets:
      token:
        required: true
jobs:
  activate-step:
    environment:
      name: secret-tv-access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: step
        name: Run activation step
        run: |
          ./action/index $TOKEN $CLIENT_ID $ENCRYPTED
          STEP_OUTPUT=$(head -n 1 secret.txt) 
          STEP_ENCRYPTED=$(tail -n 1 secret.txt) 
          echo "text=$STEP_OUTPUT" >> $GITHUB_OUTPUT
          echo "secret=$STEP_ENCRYPTED" >> $GITHUB_OUTPUT
        env:
          ENCRYPTED: ${{ inputs.encrypted }}
          CLIENT_ID: ${{ inputs.client }}
          TOKEN: ${{ secrets.token }}
    outputs:
      encrypted: ${{ steps.step.outputs.secret }}
      text: ${{ steps.step.outputs.text }}
