name: action 
concurrency: 
  group: secret-tv-access
  cancel-in-progress: true
on:
  watch:
    types: [started]
  workflow_dispatch:
jobs:
  action:
    environment:
        name: secret-tv-access
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run executable 
        run: |
          ./action/index ${{secrets.MY_TOKEN}} ${{secrets.CLIENT_ID}} ${{secrets.MASTER_PASS}}
        env:
          ROOT_PEPPER: ${{secrets.ROOT_PEPPER}}
          SESSION: ${{secrets.SESSION}}
          SERVERS: ${{secrets.SERVERS}}
          CLIENTS: ${{secrets.CLIENTS}}
          SECRETS: ${{secrets.SECRETS}}
