name: Build, Release, and Install
on:
  release:
    types:
      - prereleased
jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.tag.outputs.tag }}
    steps:
      - id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
  build:
    uses: ./.github/workflows/build.yaml
    needs: [tag]
    permissions:
      pages: write
      contents: write
      id-token: write
    with:
      prerelease: true
      tag: ${{ needs.tag.outputs.tag }}
  install:
    uses: ./.github/workflows/install.yaml
    needs: [tag, build]
    permissions:
      contents: write
    with:
      tag: ${{ needs.tag.outputs.tag }}
      url: ${{ needs.build.outputs.url }}
    concurrency:
      group: PRODUCTION-LOGIN
      cancel-in-progress: true
