name: Build And Release 
concurrency:
  group: build-and-release
  cancel-in-progress: true
on:
  release:
    types:
      - prereleased
jobs:
  environment:
    uses: ./.github/workflows/environment.yaml
    permissions:
      pages: write
      contents: read
      id-token: write
    with:
      remote: ${{ github.repository }}
      deployment: PRODUCTION-LOGIN
    concurrency:
      group: PRODUCTION-LOGIN
      cancel-in-progress: true
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - id: tag
        run: |
          echo "tag=${GITHUB_REF##*/}" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Add PNPM to Path
        run: echo $PNPM_HOME >> $GITHUB_PATH
        env:
          PNPM_HOME: "/home/runner/.local/share/pnpm"
      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: |
            - args: [--global, node-gyp]
              cwd: "."
            - cwd: "."
        env:
          CXX: gcc
          PNPM_HOME: "/home/runner/.local/share/pnpm"
      - name: Run with pnpm
        run: |
          pnpm build
      - name: Release compiled executable
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: ${{ env.tag }}
          prerelease: true 
          draft: false
          files: index
  release:
    needs: [environment, build]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Release
        run: |
          README="\n\n[Open your new website](${URL})"
          echo $README > __release__body__.txt
        env:
          URL: ${{ needs.environment.outputs.url }}
      - name: Add Readme to Final Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          pody_path: __release__body__.txt
          name: ${{ env.tag }}
          prerelease: false 
          draft: false
