name: Set environment.csv
on:
  workflow_call:
    inputs:
      remote:
        required: true
        type: string
      deployment:
        required: true
        type: string
jobs:
  pages:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v2
      - run: |
          echo "" > $CSV
          echo "REMOTE,$REMOTE" >> $CSV
          echo "DEPLOYMENT,$DEPLOYMENT" >> $CSV
        env:
          CSV: "docs/environment.csv"
          REMOTE: ${{ inputs.remote }}
          DEPLOYMENT: ${{ inputs.deployment }}
      - uses: actions/upload-pages-artifact@v1
        with: { path : 'docs' }
      - id: deployment
        uses: actions/deploy-pages@v1
