name: Register after new issues 
on:
  issues:
    types: [opened, reopened]
env:
  ROOT: "https://api.github.com"
  REMOTE: ${{ github.repository }}
  DEPLOYMENT: PRODUCTION-LOGIN
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: true
permissions:
  pages: write
  contents: read
  id-token: write
  deployments: write
jobs:
  code_and_token:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.pages.outputs.pages }}
    env:
      CSV: "environment.csv"
    steps:
      - name: Configure Pages Url
        id: pages
        run: |
          JSON=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          $ROOT/repos/$REMOTE/pages);
          PAGES_URL=$(jq -r '.html_url' <<< $JSON);
          echo "pages=$PAGES_URL" >> $GITHUB_OUTPUT
      - name: Configure Latest Release URL
        id: index
        run: |
          JSON=$(curl -s $ROOT/repos/$REMOTE/releases/latest)
          URL=$(jq -r '.assets[0].browser_download_url' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
      - uses: actions/checkout@v3
        with: { fetch-depth: 1 }
      - uses: actions/configure-pages@v2
      - name: Publish Opaque codes on Pages
        run: |
          echo "" > secret.txt
          curl -L -o index $INDEX_URL
          chmod +x index
          ./index SETUP PUB OPAQUE
          echo $(head -n 1 secret.txt) > docs/pub.txt
          wc -c docs/pub.txt
          curl -o "docs/$CSV" "$PAGES/$CSV"
          STATE=$(tail -n 1 secret.txt)
          echo "::add-mask::$STATE"
          echo "state=$STATE" >> $GITHUB_ENV
        env:
          INDEX_URL: ${{ steps.index.outputs.index }}
          PAGES: ${{ steps.pages.outputs.pages }}
      - uses: actions/upload-pages-artifact@v1
        with: { path : 'docs' }
      - uses: actions/deploy-pages@v1
      - name: Create GitHub App and share Auth to Pages
        run: |
          curl -L -o index $INDEX_URL
          chmod +x index
          ./index SETUP APP "${{ env.state }}"
          echo $(head -n 1 secret.txt) > docs/pub.txt
          curl -o "docs/$CSV" "$PAGES/$CSV"
          STATE=$(tail -n 1 secret.txt)
          echo "::add-mask::$STATE"
          echo "state=$STATE" >> $GITHUB_ENV
        env:
          INDEX_URL: ${{ steps.index.outputs.index }}
          PAGES: ${{ steps.pages.outputs.pages }}
      - uses: actions/upload-pages-artifact@v1
        with: { path : 'docs' }
      - uses: actions/deploy-pages@v1
      - name: Install App and share token to Pages
        run: |
          curl -L -o index $INDEX_URL
          chmod +x index
          ./index SETUP TOKEN "${{ env.state }}"
          echo $(head -n 1 secret.txt) > docs/pub.txt
          curl -o "docs/$CSV" "$PAGES/$CSV"
        env:
          INDEX_URL: ${{ steps.index.outputs.index }}
          PAGES: ${{ steps.pages.outputs.pages }}
      - uses: actions/upload-pages-artifact@v1
        with: { path : 'docs' }
      - uses: actions/deploy-pages@v1
