name: Close Login
on:
  repository_dispatch:
    types: [call-login-close]
env:
  DEPLOYMENT: PRODUCTION-LOGIN
  REMOTE: ${{ github.repository }}
  ROOT: "https://api.github.com"
  API: "X-GitHub-Api-Version: 2022-11-28"
  OCTET: "Accept: application/octet-stream"
  VND: "Accept: application/vnd.github+json"
  AUTH: "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: true
permissions:
  contents: write
jobs:
  login_close:
    environment:
      name: PRODUCTION-LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Configure Latest Release URL
        id: index
        run: |
          JSON=$(curl -s \
            -H "$API" -H "$AUTH" -H "$VND"\
            $ROOT/repos/$REMOTE/releases/latest)
          ID=$(jq -r '.id' <<< $JSON)
          URL=$(jq -r '.assets[0].url' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
          echo "release=$ID" >> $GITHUB_OUTPUT
      - name: Login Close
        run: |
          curl --location-trusted -H "$API" -H "$AUTH" -H "$OCTET" -o index "$INDEX_URL"
          chmod +x index
          echo "" > secret.txt
          ./index LOGIN CLOSE OUTBOX "$OP"
          STEP=$(head -n 1 secret.txt)
          MESSAGE="Use your private login link."
          ./index SHARE "$GITHUB_TOKEN" "$RELEASE" "$STEP" "$MESSAGE"
        env:
          MAIL__TABLE: ${{ secrets.MAIL__TABLE }}
          LAST__STEP: ${{ secrets.LAST__STEP }}
          ROOT__SESSION : ${{ secrets.ROOT__SESSION }}
          ROOT__INSTALLATION : ${{ secrets.ROOT__INSTALLATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INDEX_URL: ${{ steps.index.outputs.index }}
          RELEASE: ${{ steps.index.outputs.release }}
          OP: ${{ github.event.client_payload.op }}
