name: Login after Deployment
on:
  deployment:
  workflow_dispatch:
env:
  ROOT: "https://api.github.com"
  REMOTE: ${{ github.repository }}
  DEPLOYMENT: PRODUCTION-LOGIN
concurrency:
  group: PRODUCTION-LOGIN-DEPLOYMENT
  cancel-in-progress: true
jobs:
  login:
    permissions:
      deployments: read
    environment:
      name: PRODUCTION-LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Validate Deployment Environment
        id: filter
        run: |
          JSON=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          $ROOT/repos/$REMOTE/deployments?environment=$START);
          OUTPUT=$(jq -r '.[0].environment' <<< $JSON);
          echo "deployment environment is $OUTPUT";
          echo "approved=$OUTPUT" >> $GITHUB_OUTPUT
          echo "wanted=$START" >> $GITHUB_OUTPUT
        env:
          START: ${{ env.DEPLOYMENT }}-START
      - name: Download Latest Release
        if: steps.filter.outputs.approved == steps.filter.outputs.wanted
        id: index
        run: |
          echo ${{steps.filter.outputs.approved}}
          JSON=$(curl -s $ROOT/repos/$REMOTE/releases/latest)
          URL=$(jq -r '.assets[0].browser_download_url' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
      - name: User Login
        if: steps.filter.outputs.approved == steps.filter.outputs.wanted
        run: |
          curl -L -o index $INDEX_URL
          chmod +x index
          ./index $ROOT_TOKEN
        env:
          INDEX_URL: ${{ steps.index.outputs.index }}
          ROOT_PEPPER: ${{secrets.ROOT_PEPPER}}
          ROOT_TOKEN: ${{secrets.ROOT_TOKEN}}
          SESSION: ${{secrets.SESSION}}
          SERVERS: ${{secrets.SERVERS}}
          CLIENTS: ${{secrets.CLIENTS}}
          SECRETS: ${{secrets.SECRETS}}
