name: Open Login
on:
  repository_dispatch:
    types: [call-login-open]
env:
  ROOT: "https://api.github.com"
  REMOTE: ${{ github.repository }}
  DEPLOYMENT: PRODUCTION-LOGIN
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: true
permissions:
  issues: read
  contents: write
jobs:
  login_open:
    environment:
      name: PRODUCTION-LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Configure Latest Release URL
        id: index
        run: |
          JSON=$(curl -s $ROOT/repos/$REMOTE/releases/latest)
          URL=$(jq -r '.assets[0].browser_download_url' <<< $JSON)
          ID=$(jq -r '.id' <<< $JSON)
          BODY=$(jq -r '.body' <<< $JSON)
          CTLI=$(echo "$BODY" | head -n1)
          echo "index=$URL" >> $GITHUB_OUTPUT
          echo "release=$ID" >> $GITHUB_OUTPUT
          echo "ctli=$CTLI" >> $GITHUB_OUTPUT
      - name: Login Open
        run: |
          curl -L -o index $INDEX_URL
          chmod +x index
          echo "" > secret.txt
          ./index LOGIN OPEN "$PUB_CTLI" "$OP"
          STEP=$(head -n 1 secret.txt)
          MESSAGE="Use your private login link."
          ./index SHARE $GITHUB_TOKEN $RELEASE $STEP "$MESSAGE"
        env:
          INSTALLATION : ${{ secrets.INSTALLATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUB_CTLI: ${{ steps.index.outputs.ctli }}
          INDEX_URL: ${{ steps.index.outputs.index }}
          RELEASE: ${{ steps.index.outputs.release }}
          OP: ${{ github.event.client_payload.op }}
