name: Login after Dispatch
on:
  repository_dispatch:
    types: [PRODUCTION-LOGIN-START]
env:
  ROOT: "https://api.github.com"
  REMOTE: ${{ github.repository }}
  DEPLOYMENT: PRODUCTION-LOGIN
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: true
permissions: {}
jobs:
  login:
    environment:
      name: PRODUCTION-LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Find Latest Release
        id: index
        run: |
          echo $DEPLOYMENT
          JSON=$(curl -s $ROOT/repos/$REMOTE/releases/latest)
          URL=$(jq -r '.assets[0].browser_download_url' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
      - name: User Login
        run: |
          curl -L -o index $INDEX_URL
          chmod +x index
          ./index LOGIN $ROOT_TOKEN
        env:
          OLD_HASH: ${{ github.event.client_payload.reset-key }}
          INDEX_URL: ${{ steps.index.outputs.index }}
          ROOT_PEPPER: ${{secrets.ROOT_PEPPER}}
          ROOT_TOKEN: ${{secrets.ROOT_TOKEN}}
          SESSION: ${{secrets.SESSION}}
          SERVERS: ${{secrets.SERVERS}}
          CLIENTS: ${{secrets.CLIENTS}}
          SECRETS: ${{secrets.SECRETS}}
