name: Update Token
on:
  schedule:
    - cron: '4 11-23/2 * * *'
    - cron: '19 12-22/2 * * *'
    - cron: '34 11-23/2 * * *'
    - cron: '49 12-22/2 * * *'
  workflow_dispatch:
env:
  ROOT: "https://api.github.com"
  REMOTE: ${{ github.repository }}
  DEPLOYMENT: PRODUCTION-LOGIN
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: false
permissions:
  issues: read
  contents: write
jobs:
  reset_token:
    environment:
      name: PRODUCTION-LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Configure Latest Release URL
        id: index
        run: |
          JSON=$(curl -s $ROOT/repos/$REMOTE/releases/latest)
          URL=$(jq -r '.assets[0].browser_download_url' <<< $JSON)
          ID=$(jq -r '.id' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
          echo "release=$ID" >> $GITHUB_OUTPUT
          echo "body=$BODY" >> $GITHUB_OUTPUT
      - name: Login Open
        run: |
          curl -L -o index $INDEX_URL
          chmod +x index
          echo "" > secret.txt
          ./index UPDATAE TOKEN "$PUB_CTLI"
          STEP=$(head -n 1 secret.txt)
          MESSAGE="Use your private login link."
          ./index SHARE "$GITHUB_TOKEN" "$RELEASE" "$STEP" "$MESSAGE"
        env:
          INSTALLATION : ${{ secrets.INSTALLATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUB_CTLI: ${{ steps.index.outputs.body }}
          INDEX_URL: ${{ steps.index.outputs.index }}
          RELEASE: ${{ steps.index.outputs.release }}
