name: Update Token
on:
  schedule:
    - cron: '4 11-23/2 * * *'
    - cron: '19 12-22/2 * * *'
    - cron: '34 11-23/2 * * *'
    - cron: '49 12-22/2 * * *'
  workflow_dispatch:
env:
  DEPLOYMENT: PRODUCTION-LOGIN
  REMOTE: ${{ github.repository }}
  ROOT: "https://api.github.com"
  API: "X-GitHub-Api-Version: 2022-11-28"
  OCTET: "Accept: application/octet-stream"
  VND: "Accept: application/vnd.github+json"
  AUTH: "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"
concurrency:
  group: PRODUCTION-LOGIN
  cancel-in-progress: false
permissions:
  contents: write
jobs:
  reset_token:
    environment:
      name: PRODUCTION-LOGIN
    runs-on: ubuntu-latest
    steps:
      - name: Configure Latest Release URL
        id: index
        run: |
          JSON=$(curl -s \
            -H "$API" -H "$AUTH" -H "$VND"\
            $ROOT/repos/$REMOTE/releases/latest)
          BODY=$(jq -r '.body' <<< $JSON)
          ID=$(jq -r '.id' <<< $JSON)
          PUB=$(echo "$BODY" | head -n1)
          URL=$(jq -r '.assets[0].url' <<< $JSON)
          echo "index=$URL" >> $GITHUB_OUTPUT
          echo "release=$ID" >> $GITHUB_OUTPUT
          echo "pub=$PUB" >> $GITHUB_OUTPUT
      - name: Login Open
        run: |
          curl --location-trusted -H "$API" -H "$AUTH" -H "$OCTET" -o index "$INDEX_URL"
          chmod +x index
          echo "" > secret.txt
          ./index UPDATAE TOKEN "$PUB"
          STEP=$(head -n 1 secret.txt)
          MESSAGE="Use your private login link."
          ./index SHARE "$GITHUB_TOKEN" "$RELEASE" "$STEP" '"'"$MESSAGE"'"'
        env:
          PUB: ${{ steps.index.outputs.pub }}
          INSTALLATION : ${{ secrets.INSTALLATION }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          INDEX_URL: ${{ steps.index.outputs.index }}
          RELEASE: ${{ steps.index.outputs.release }}
