name: wiki 
on:
  gollum:
permissions:
  pages: write
  contents: read
  id-token: write
concurrency:
  group: secret-tv-access
  cancel-in-progress: true
jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Create Environment
        run: |
          curl \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          $ROOT/repos/$REPO/environments/$STAGE
        env:
          ROOT: "https://api.github.com"
          REPO: ${{ github.repository }}
          STAGE: "secret-tv-access"
      - id: client
        name: Read client ID
        run: |
          JSON=$(curl \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{github.token}}" \
          $ROOT/repos/$REPO);
          CLIENT=$(jq -r '.description' <<< $JSON);
          echo "Using OAuth App $CLIENT";
          echo "client=$CLIENT" >> $GITHUB_OUTPUT
        env:
          ROOT: "https://api.github.com"
          REPO: ${{ github.repository }}
    outputs:
      client: ${{ steps.client.outputs.client }}
  get-code:
    needs: [setup]
    uses: ./.github/workflows/activate.yaml
    with:
      client: ${{ needs.setup.outputs.client }}
    secrets:
      token: ${{ github.token }}
  push-code:
    needs: [get-code]
    uses: ./.github/workflows/pages.yaml
    with:
      contents: ${{ needs.get-code.outputs.text }}
  get-token:
    needs: [setup, get-code, push-code]
    uses: ./.github/workflows/activate.yaml
    with:
      client: ${{ needs.setup.outputs.client }}
      encrypted: ${{ needs.get-code.outputs.encrypted }}
    secrets:
      token: ${{ github.token }}
  push-token:
    needs: [get-token]
    uses: ./.github/workflows/pages.yaml
    with:
      contents: ${{ needs.get-token.outputs.text }}
  register:
    needs: [setup, get-token, push-token]
    uses: ./.github/workflows/activate.yaml
    with:
      client: ${{ needs.setup.outputs.client }}
      encrypted: ${{ needs.get-token.outputs.encrypted }}
    secrets:
      token: ${{ github.token }}
  cleanup:
    needs: [register]
    uses: ./.github/workflows/pages.yaml
    with:
      contents: ${{ needs.register.outputs.text }}
